---
title: "[`Plotly`](https://github.com/ShahyarTaheri/ioslides-plotly) project"
author: "Shahyar Taheri"
date: "12/21/2018"
output:
  iosp::ioslides_plus:
    fig_height: 5
    fig_width: 6
    keep_md: no
    logo: img/uni.png
    smaller: no
    widescreen: yes
    self_contained: false
    lib_dir: libs
    fig_retina: null
---

```{r, echo=FALSE, message=FALSE}
library(plotly)
```

# Boxplot

## Boxplot {.flexbox .vcenter}

```{r, echo=FALSE, warning=FALSE, cache=FALSE, message=FALSE}

p <- plot_ly(ggplot2::diamonds, x = ~cut, y = ~price, color = ~clarity, type = "box") %>%
  layout(boxmode = "group")
p
```

# Plot with menus

## Plot with menus {.flexbox .vcenter}

```{r, echo=FALSE, message=FALSE}
library(MASS)

covmat <- matrix(c(0.8, 0.4, 0.3, 0.8), nrow = 2, byrow = T)
df <- mvrnorm(n = 10000, c(0,0), Sigma = covmat)
df <- as.data.frame(df)

colnames(df) <- c("x", "y")
plot_ly(df, x = ~x, y = ~y, alpha = 0.3) %>%
  add_markers(marker = list(line = list(color = "black", width = 1))) %>%
  layout(
    title = "Drop down menus - Plot type",
    xaxis = list(domain = c(0.1, 1)),
    yaxis = list(title = "y"),
    updatemenus = list(
      list(
        y = 0.8,
        buttons = list(

          list(method = "restyle",
               args = list("type", "scatter"),
               label = "Scatter"),

          list(method = "restyle",
               args = list("type", "histogram2d"),
               label = "2D Histogram")))
    ))

```


